# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('comment', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialect', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbackmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacktext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=6)),
                ('order', models.CharField(blank=True, max_length=3)),
                ('feedbackmsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.Feedbackmsg')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullform', models.CharField(max_length=200)),
                ('no_show', models.BooleanField(default=False)),
                ('dialects', models.ManyToManyField(blank=True, to='drill.Dialect')),
                ('feedback', models.ManyToManyField(blank=True, to='drill.Feedbackmsg')),
            ],
        ),
        migrations.CreateModel(
            name='Grammarlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=800, null=True)),
                ('language', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkUtterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=20, null=True)),
                ('variable', models.CharField(blank=True, max_length=20, null=True)),
                ('constant', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('userinput', models.CharField(max_length=200)),
                ('iscorrect', models.BooleanField()),
                ('correct', models.TextField()),
                ('example', models.CharField(max_length=200, null=True)),
                ('feedback', models.CharField(max_length=200, null=True)),
                ('comment', models.CharField(max_length=200)),
                ('messageid', models.CharField(max_length=100, null=True)),
                ('lang', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MorphPhonTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=20)),
                ('wordclass', models.CharField(max_length=20)),
                ('diphthong', models.CharField(max_length=20)),
                ('gradation', models.CharField(max_length=20)),
                ('rime', models.CharField(max_length=20)),
                ('soggi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syntax', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=20)),
                ('gametype', models.CharField(max_length=7)),
                ('game', models.CharField(max_length=20)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_set', to='drill.QElement')),
                ('copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_set', to='drill.QElement')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('task', models.CharField(max_length=20)),
                ('string', models.CharField(max_length=200)),
                ('qtype', models.CharField(max_length=20)),
                ('qatype', models.CharField(max_length=20)),
                ('gametype', models.CharField(max_length=7)),
                ('lemmacount', models.IntegerField()),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='drill.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Semtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=60, unique=True)),
                ('attributive', models.CharField(max_length=5)),
                ('case', models.CharField(max_length=5)),
                ('conneg', models.CharField(max_length=5)),
                ('grade', models.CharField(max_length=10)),
                ('infinite', models.CharField(max_length=10)),
                ('mood', models.CharField(max_length=5)),
                ('number', models.CharField(max_length=5)),
                ('personnumber', models.CharField(max_length=8)),
                ('polarity', models.CharField(max_length=5)),
                ('pos', models.CharField(max_length=12)),
                ('possessive', models.CharField(max_length=5)),
                ('diminutive', models.CharField(max_length=10)),
                ('subclass', models.CharField(max_length=10)),
                ('tense', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tagname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tagset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagset', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.Dialogue')),
                ('formlist', models.ManyToManyField(to='drill.Form')),
            ],
        ),
        migrations.CreateModel(
            name='UElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syntax', models.CharField(max_length=50)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance', models.CharField(blank=True, max_length=500, null=True)),
                ('utttype', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('formlist', models.ManyToManyField(to='drill.Form')),
                ('links', models.ManyToManyField(to='drill.LinkUtterance')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordid', models.CharField(db_index=True, max_length=200)),
                ('language', models.CharField(db_index=True, default=b'sme', max_length=5)),
                ('lemma', models.CharField(db_index=True, max_length=200)),
                ('presentationform', models.CharField(max_length=5)),
                ('pos', models.CharField(max_length=12)),
                ('stem', models.CharField(max_length=20)),
                ('wordclass', models.CharField(max_length=8)),
                ('valency', models.CharField(max_length=10)),
                ('hid', models.IntegerField(default=None, null=True)),
                ('hom', models.CharField(max_length=4)),
                ('diphthong', models.CharField(max_length=5)),
                ('gradation', models.CharField(max_length=20)),
                ('rime', models.CharField(max_length=20)),
                ('attrsuffix', models.CharField(max_length=20)),
                ('compsuffix', models.CharField(max_length=20)),
                ('soggi', models.CharField(max_length=10)),
                ('compare', models.CharField(max_length=5)),
                ('frequency', models.CharField(max_length=10)),
                ('geography', models.CharField(max_length=10)),
                ('tcomm', models.BooleanField(default=False)),
                ('dialects', models.ManyToManyField(blank=True, to='drill.Dialect')),
                ('morphophon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.MorphPhonTag')),
                ('semtype', models.ManyToManyField(to='drill.Semtype')),
                ('source', models.ManyToManyField(to='drill.Source')),
            ],
        ),
        migrations.CreateModel(
            name='WordQElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qelement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.QElement')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=5)),
                ('wordid', models.CharField(db_index=True, max_length=200)),
                ('lemma', models.CharField(blank=True, max_length=200)),
                ('phrase', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('pos', models.CharField(max_length=12)),
                ('frequency', models.CharField(max_length=10)),
                ('geography', models.CharField(max_length=10)),
                ('tcomm', models.BooleanField(default=False)),
                ('tcomm_pref', models.BooleanField(default=False)),
                ('semtype', models.ManyToManyField(to='drill.Semtype')),
                ('source', models.ManyToManyField(to='drill.Source')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.Word')),
            ],
        ),
        migrations.AddField(
            model_name='uelement',
            name='utterance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.Utterance'),
        ),
        migrations.AddField(
            model_name='tagname',
            name='tagset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.Tagset'),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.ManyToManyField(to='drill.Source'),
        ),
        migrations.AddField(
            model_name='qelement',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.Question'),
        ),
        migrations.AddField(
            model_name='qelement',
            name='semtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.Semtype'),
        ),
        migrations.AddField(
            model_name='qelement',
            name='tags',
            field=models.ManyToManyField(to='drill.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='morphphontag',
            unique_together=set([('stem', 'wordclass', 'diphthong', 'gradation', 'rime', 'soggi')]),
        ),
        migrations.AddField(
            model_name='linkutterance',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drill.Utterance'),
        ),
        migrations.AddField(
            model_name='form',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.Tag'),
        ),
        migrations.AddField(
            model_name='form',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.Word'),
        ),
    ]
