# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrsuffix', models.CharField(blank=True, max_length=10, null=True)),
                ('soggi', models.CharField(blank=True, max_length=10, null=True)),
                ('stem', models.CharField(blank=True, max_length=20, null=True)),
                ('wordclass', models.CharField(blank=True, max_length=20, null=True)),
                ('attributive', models.CharField(blank=True, max_length=10, null=True)),
                ('case2', models.CharField(blank=True, max_length=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('mood', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.CharField(blank=True, max_length=5, null=True)),
                ('personnumber', models.CharField(blank=True, max_length=5, null=True)),
                ('pos', models.CharField(blank=True, max_length=12, null=True)),
                ('tense', models.CharField(blank=True, max_length=5, null=True)),
                ('dialects', models.ManyToManyField(to='drill.Dialect')),
                ('messages', models.ManyToManyField(to='drill.Feedbackmsg')),
            ],
        ),
        migrations.RemoveField(
            model_name='linkutterance',
            name='link',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='dialogue',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='formlist',
        ),
        migrations.RemoveField(
            model_name='uelement',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='uelement',
            name='utterance',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='formlist',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='links',
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='feedbacktext',
            name='order',
        ),
        migrations.RemoveField(
            model_name='form',
            name='dialects',
        ),
        migrations.RemoveField(
            model_name='form',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='form',
            name='no_show',
        ),
        migrations.RemoveField(
            model_name='log',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='log',
            name='messageid',
        ),
        migrations.RemoveField(
            model_name='qelement',
            name='task',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lemmacount',
        ),
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='diminutive',
        ),
        migrations.RemoveField(
            model_name='word',
            name='hid',
        ),
        migrations.AddField(
            model_name='log',
            name='user_country',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='qelement',
            name='gametype',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='gametype',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tag',
            name='string',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='word',
            name='dialects',
            field=models.ManyToManyField(null=True, to='drill.Dialect'),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(db_index=True, default=b'sma', max_length=5),
        ),
        migrations.DeleteModel(
            name='Dialogue',
        ),
        migrations.DeleteModel(
            name='LinkUtterance',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='UElement',
        ),
        migrations.DeleteModel(
            name='Utterance',
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set([('pos', 'stem', 'soggi', 'wordclass', 'case2', 'number', 'personnumber', 'tense', 'mood', 'grade', 'attrsuffix', 'attributive')]),
        ),
    ]
