# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0002_auto_20180629_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='dialects',
            field=models.ManyToManyField(null=True, to='drill.Dialect'),
        ),
    ]
