# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0004_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hid',
            field=models.IntegerField(default=None, max_length=3, null=True),
        ),
    ]
