# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('game', models.CharField(blank=True, max_length=10)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('confirmation', models.BooleanField()),
                ('confirmed_by', models.CharField(blank=True, max_length=20)),
                ('comments', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
