cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ABSTRACT"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ABSTRACT.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ACTION"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ACTION.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ACTION_V"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ACTION_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ACTOR"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ACTOR.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"AMOUNT"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_AMOUNT.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ANIMAL_A"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ANIMAL_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ANIMAL_DOM"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ANIMAL_DOM.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ANIMAL_OTHER"'   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ANIMAL_OTHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ANIMAL_PET"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ANIMAL_PET.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ANIMAL_V"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ANIMAL_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ANIMAL_WILD"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ANIMAL_WILD.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ARRANGEMENT"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ARRANGEMENT.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"AUX_V"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_AUX_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"BATHROOM"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_BATHROOM.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"BIRD"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_BIRD.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"BODYPART"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_BODYPART.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"BODY_A"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_BODY_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"BODY_V"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_BODY_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"BUILDING"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_BUILDING.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"CHRISTMAS"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_CHRISTMAS.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"CLOTHES_A"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_CLOTHES_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"CLOTHES_V"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_CLOTHES_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"CLOTHING"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_CLOTHING.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"CLOTHING_OTHER"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_CLOTHING_OTHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"CLOTHING_PL"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_CLOTHING_PL.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"CONTAINER"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_CONTAINER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"DRINK"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_DRINK.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"EDUCATION"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_EDUCATION.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"EXPERIENCE_A"'   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_EXPERIENCE_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"EXPERIENCE_V"'   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_EXPERIENCE_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"EXPOSURE_V"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_EXPOSURE_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FAMILY"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FAMILY.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FEELING"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FEELING.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FINANCE"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FINANCE.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FISH"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FISH.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FISHING"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FISHING.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FOOD_DISH"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FOOD_DISH.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FOOD_DRINK_V"'   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FOOD_DRINK_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FOOD_GROCERY"'   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FOOD_GROCERY.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FOOD_OTHER"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FOOD_OTHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FURNITURE"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FURNITURE.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"GAMME"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_GAMME.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"HANDICRAFTS"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_HANDICRAFTS.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"HERDING"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_HERDING.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"HOME_ACTIVITY"'  | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_HOME_ACTIVITY.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"HUMAN_A"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_HUMAN_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"HUMAN_V"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_HUMAN_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ILLNESS"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ILLNESS.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"INSTRUMENT"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_INSTRUMENT.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"JOB"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_JOB.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"KITCHEN"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_KITCHEN.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"LANGUAGE"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_LANGUAGE.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"LANGUAGEPART"'   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_LANGUAGEPART.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep LEISURETIME_HO | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_LEISURETIME_HOME_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"MOVEMENT_A"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_MOVEMENT_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"MOVEMENT_V"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_MOVEMENT_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"MYTH_HUMAN"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_MYTH_HUMAN.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"NATURE"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_NATURE.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"NATURE_A"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_NATURE_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"NATURE_PLACE"'   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_NATURE_PLACE.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"NATURE_V"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_NATURE_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"NATURE_WATER"'   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_NATURE_WATER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"OBJECT_A"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_OBJECT_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ORGANIZATION"'   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ORGANIZATION.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"PEOPLE"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_PEOPLE.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"PLACE_LOCAL"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_PLACE_LOCAL.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"PLACE_OTHER"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_PLACE_OTHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"PLACE_STAYING"'  | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_PLACE_STAYING.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"PLANT"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_PLANT.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"PROFESSION"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_PROFESSION.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"REINDEER"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_REINDEER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ROAD"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ROAD.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ROOM"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ROOM.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ROOM_OTHER"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ROOM_OTHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ROOM_PART"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ROOM_PART.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SCHOOL"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SCHOOL.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SCHOOL_A"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SCHOOL_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SCHOOL_V"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SCHOOL_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SHOP"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SHOP.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SHOW"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SHOW.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SLEEPINGROOM"'  | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SLEEPINGROOM.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SLIDE_TOOL"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SLIDE_TOOL.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SNOW"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SNOW.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SOUND"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SOUND.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SOUP_A"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SOUP_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SPORT"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SPORT.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TEXT"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TEXT.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"THING"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_THING.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"THOUGHT"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_THOUGHT.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TIME"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TIME.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TIME_A"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TIME_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TIME_V"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TIME_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TOOL"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TOOL.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TOY"'			   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TOY.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TRAD_CLOTHING"'  | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TRAD_CLOTHING.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TRAD_FOOD"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TRAD_FOOD.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TRAD_OBJECT"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TRAD_OBJECT.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TRAD_OTHER"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TRAD_OTHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TRAVELLING"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TRAVELLING.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TRAVEL_V"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TRAVEL_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"VEHICLE"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_VEHICLE.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"VERBAL_V"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_VERBAL_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"VUEKIE"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_VUEKIE.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"VÆTNOE"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_VÆTNOE.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"WEATHER"'		   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_WEATHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"WEATHER_A"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_WEATHER_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"WEATHER_V"'	   | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_WEATHER_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"WORK_ECONOMY_V"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_WORK_ECONOMY_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TIME_U"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TIME_U.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"EXPRESSIONS"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_EXPRESSIONS.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ACTIVITY_V"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ACTIVITY_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"BIRD_FISH_OTHER"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_BIRD_FISH_OTHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"BIRD_FISH_V"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_BIRD_FISH_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"BODY_ADV"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_BODY_ADV.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ISSUE_adj"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ISSUE_adj.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"LEISURETIME_HOME_V"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_LEISURETIME_HOME_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"MORFAC"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_MORFAC.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"NATURE_OTHER"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_NATURE_OTHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"NUMBER"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_NUMBER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"PLACE_COUNTRY"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_PLACE_COUNTRY.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"PLACE_NAME"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_PLACE_NAME.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"PLACE_NATURE"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_PLACE_NATURE.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"PRON"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_PRON.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"SCHOOL_ADV"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_SCHOOL_ADV.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"ANIMAL_SOUND_V"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_ANIMAL_SOUND_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"BUILDING_ROOM_A"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_BUILDING_ROOM_A.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"COMMAND_V"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_COMMAND_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FAMILY_OTHER"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FAMILY_OTHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"FINANCE_V"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_FINANCE_V.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"STORY"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_STORY.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TEXT_OTHER"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TEXT_OTHER.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TIME_DAY"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TIME_DAY.jspwiki
cat *smanob.xml | sed 's/<\/e>/<\/e>$/' | tr "\n" " " | tr "$" "\n" | grep '"TRAVELLING_V"' | cut -d">" -f4 | cut -d"<" -f1 | sort | sed 's/^/* /' > sem_sett/Sem_TRAVELLING_V.jspwiki
