// Generated by CoffeeScript 1.3.3

﻿chrome.contextMenus.create({
  title: "Oza '%s' sátnegirjjis",
  contexts: ["page", "selection"],
  onclick: function(info, tab) {
    var notification;
    notification = webkitNotifications.createHTMLNotification("http://testing.oahpa.no/kursadict/notify/sme/nob/" + info.selectionText + ".html");
    return notification.show();
  }
});
