sed 's/^/PV\/e\+wîkiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e > allparadigms.txt
sed 's/^/PV\/e\+atoskêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+itohtêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+isiyihkâsow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+itwêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kiskinwahamâkosiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nêhiyawêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+itamahcihow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+miyomahcihow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nêstosiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nôhtêhkatêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nôhtêhkwasiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+mihkosiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kaskitêsiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wâpiskisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+askihtakosiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+sîpihkosiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wâposâwisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+miyosiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+katawasisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+misikitiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kakwêyâhow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+apisîsisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+maskawisîw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wîhkitisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+osâwisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wîpôsâwisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wâpikwanîwinâkosiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+watôkimihkosiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pihkonâkosiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kinosiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+cimisisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+mâyâtisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+yîkicikâwîw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wiyipâtisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pîkopayiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kanâtisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pôsiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+têhtapiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+itâpiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pâhpisiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+waskawîw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+piminawasow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+waniskâw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pasikôw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wayawîw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+sipwêhtêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+apiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pêhow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+akihcikêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+itahtopiponêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+sôniyâhkêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+otahowêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kocîw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+âkayâsîmow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+ayamihâw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pimipahtâw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+têpwêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+otâpâsow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nipâw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+mâtow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+mîcisow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pimohtêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pîkiskwêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+minihkwêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nikamow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+masinahikêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+ayamihcikêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pîhtwâw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+ohpîw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nîpawiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+mêtawêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pâhpiw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nîmihitow\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kîwêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pîhtokwêw\+/' AIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+isiyihkâcikâtêw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+mihkwâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kaskitêwâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wâpiskâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+askihtakwan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+sîpihkwâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wâposâwâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+miywâsin\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+katawasisin\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+misâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kakwêyâhômakan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+apisâsin\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+maskihkîwimâkwan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wîhkasin\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+osâwâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wîposâwâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wâpikwanîwinâkwan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+watôkimihkwâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pihkonâkwan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kinwâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+ispâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+cimâsin\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+mâyâtan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+yikicikâwîmakan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wiyipâtan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pîkopayin\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kanâtan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+ayâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+âpihtâ-kîsikâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+âpihtâ-tipiskâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kîsikâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+tipiskâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wâpan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pêtâpan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+otâkosin\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kîkisêpâyâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+ayamihâwi-kîsikâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pôn-âyamihêwi-kîsikâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nîso-kîsikâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nisto-kîsikâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nêwo-kîsikâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+niyânano-kîsikâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nikotwâsiko-kîsikâw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+itakihtêw\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+isiwêpan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wâsêskwan\+/' IIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pêtawêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+isiyihkâtêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wâpamêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nitawêyimêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nisitawêyimêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pîkiskwâtêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wîhkistêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pôsihêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kitâpamêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+mowêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pakamahwêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nawacîw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kîsiswêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+sâminêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pôtâtêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pêhtawêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nisitohtawêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+akimêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kocîhêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pêsiwêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nâtêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+otinêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+itohtahêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+naskwênêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+tahkonêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pîkonêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nakasiwêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+ahêw\+/' TAcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+isiyihkâtâw\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wâpahtam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nitawêyihtam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nisitohtam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nitohtam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+wîhkistam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kitâpahtam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+mîciw\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pakamaham\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nawacîw\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kîsisam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+sâminam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pôtâtam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+miywêyihtam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+akihtam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+kocîhtâw\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pêtâw\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nâtam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+otinam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+itohtatâw\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+naskwênam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+tahkonam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+pîkonam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+nakatam\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/^/PV\/e\+astâw\+/' TIcnjtags |$LOOKUP $GTHOME/langs/crk/src/generator-gt-norm.xfst |grep -v '?' | grep e >> allparadigms.txt
sed 's/PV\/e\+//' allparadigms.txt > cnjparadigms.txt
rm allparadigms.txt

