cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("PEOPLE|"MYTH_HUMAN")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"PEOPLE|"MYTH_HUMAN")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/HUMAN.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '"FAMILY' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"FAMILY)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/RELATIVES.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '"PROFESSION' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"PROFESSION)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/WORKERS.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("HUMAN_V"|"HUMAN_A"|"EXPERIENCE_A"|"VERBAL_V"|"EXPERIENCE_V"|"AUX_V")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"HUMAN_V"|"HUMAN_A"|"EXPERIENCE_A"|"VERBAL_V"|"EXPERIENCE_V"|"AUX_V")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/HUMAN_DOING.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("FOOD|"DRINK|"SOUP_A)' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"FOOD|"DRINK|"SOUP_A)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/FOODDRINK.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("ANIMAL_DOM"|"ANIMAL_WILD"|"ANIMAL_PET"|"ANIMAL_PREDATOR"|"ANIMAL_HUNT"|"ANIMAL_OTHER"|"ANIMAL_V"|"ANIMAL_SOUND_V"|"ANIMAL_A")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"ANIMAL_DOM"|"ANIMAL_WILD"|"ANIMAL_PET"|"ANIMAL_PREDATOR"|"ANIMAL_HUNT"|"ANIMAL_OTHER"|"ANIMAL_V"|"ANIMAL_SOUND_V"|"ANIMAL_A")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/ANIMAL.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '(BIRD|FISH)' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |BIRD|FISH)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/BIRD_FISH.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("TOOL"|"THING"|"KITCHEN"|"BATHROOM"|"SLEEPINGROOM"|"CONTAINER"|"OBJECT_V"|"BELONGINGS")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"TOOL"|"THING"|"KITCHEN"|"BATHROOM"|"SLEEPINGROOM"|"CONTAINER"|"OBJECT_V"|"BELONGINGS")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/OBJECT.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("INSTRUMENT"|"CONTAINER"|"EXPOSURE_V"|"OBJECT_A")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"INSTRUMENT"|"CONTAINER"|"EXPOSURE_V"|"OBJECT_A")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/CONCRETES.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '(BODY|ILLNESS)' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |BODY|ILLNESS)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/BODY.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("CLOTH|"COLOUR")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"CLOTH|"COLOUR")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/CLOTHES.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '"NATURE' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"NATURE)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/NATUREWORDS.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("BUILDING|"ROOM|"SHOP|"CONSTRUCTION|"FURNITURE)' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"BUILDING|"ROOM|"SHOP|"CONSTRUCTION|"FURNITURE)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/BUILDINGSROOMS.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '"PLANT"' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"PLANT")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/PLANTS.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("WEATHER|"SNOW")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"WEATHER|"SNOW")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/WEATHERTYPES.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("ARRANGEMENT"|"SPORT"|"HOME_ACTIVITY"|"CHRISTMAS"|"SLIDE_TOOL"|"TOY"|"LEISURETIME_HOME_V"|"SHOW")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"ARRANGEMENT"|"SPORT"|"HOME_ACTIVITY"|"CHRISTMAS"|"SLIDE_TOOL"|"TOY"|"LEISURETIME_HOME_V"|"SHOW")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/LEISURETIME_AT_HOME.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("PLACE_STAYING|"PLACE_OTHER|"PLACE_LOCAL|"TRAVEL|"VEHICLE"|"ROAD"|"MOVEMENT)' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"PLACE_STAYING|"PLACE_OTHER|"PLACE_LOCAL|"TRAVEL|"VEHICLE"|"ROAD"|"MOVEMENT)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/TRAVEL.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("FEELING|"THOUGHT"|"ACTION|"ABSTRACT|"SOUND"|"AMOUNT")'  | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"FEELING|"THOUGHT"|"ACTION|"ABSTRACT|"SOUND"|"AMOUNT")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/ABSTRACTS.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("JOB|"ORGANIZATION"|"FINANCE|"TOOL|"WORK_ECONOMY_V)' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"JOB|"ORGANIZATION"|"FINANCE|"TOOL|"WORK_ECONOMY_V)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/WORK_ECONOMY_TOOLS.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("TIME"|TIME_DAY|TIME_V|TIME_A)' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"TIME"|TIME_DAY|TIME_V|TIME_A)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/TIMEEXPRESSIONS.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("TEXT|"STORY|"LANGUAGE|"ISSUE)' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"TEXT|"STORY|"LANGUAGE|"ISSUE)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/LITERATURETEXT.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("SCHOOL|"EDUCATION)' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"SCHOOL|"EDUCATION)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/SCHOOLEDUCATION.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("HERDING|"REINDEER|"NATURE_PLACE_REINDEER")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"HERDING|"REINDEER|"NATURE_PLACE_REINDEER")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/REINDEERHERDING.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("TRADITIONAL"|"FISHING"|"TRAD|"VUEKIE")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"TRADITIONAL"|"FISHING"|"TRAD|"VUEKIE")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/TRADITIONAL.txt 

cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("VÆTNOE|"HANDICRAFTS)' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"VÆTNOE|"HANDICRAFTS)' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/DUEDTIE.txt 


cat *_smanob.xml |  grep -v "<re>" | sed 's/<l /$<l /' | sed 's/<\/e>/$<\/e>/' | tr "\n" "¢" | tr "$" "\n" | grep '<l ' | egrep '("EXPRESSIONS|"TIME_U")' | sed 's/<mg/$<mg/g' | tr "$" "\n" | egrep '(<l |"EXPRESSIONS|"TIME_U")' | sed 's/<tg/$<tg/g' | tr "$" "\n" | egrep '(<l |"swe")' | tr "¢" "\n" | egrep '(<l |stat="pref")' | sed 's/<\/l>/ : /' | sed 's/<\/t.*/¢/' | tr "<" ">" | cut -d ">" -f3 | tr "\n" " " | tr "¢" "\n" | sed 's/^ //' | sort >  lists/MULTIWORD.txt 



